[project]
name = "visual-explainer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.1.2",
    "langgraph>=1.0.4",
    "tavily-python>=0.7.13",
]
